### ISSUE TITLE
Commenting gives an error in the console

### ISSUE THREAD

**Issue by rollie1212** [ali-h/hive-bot#1]
Unhandled rejection RPCError: missing required posting authority:Missing Posting Authority cryptobrewmaster
    at new RPCError (C:\Users\А\Desktop\MY TG BOTS\cbmbot\node_modules\@hivechain\hivejs\lib\api\transports\http.js:43:106)
    at C:\Users\А\Desktop\MY TG BOTS\cbmbot\node_modules\@hivechain\hivejs\lib\api\transports\http.js:93:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

any idea how to fix that? Thanks in advance

**Comment by ali-h** [comment]
Hi there, Reason for this could be that the package is not yet updated yet to support HF24. I'm looking into it. though I might be able to provide solution/help for what you are trying to do, you can contact me on discord. Thanks!
