### ISSUE TITLE
I get this api error. How can I change the api address?

### ISSUE THREAD

**Issue by qtipz** [ali-h/hive-bot#2]
Unhandled rejection FetchError: request to https://api.hive.blog failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/home/user/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by qtipz** [comment]
> Unhandled rejection FetchError: request to https://api.hive.blog failed, reason: Client network socket disconnected before secure TLS connection was established
> at ClientRequest. (/home/user/node_modules/node-fetch/index.js:133:11)
> at ClientRequest.emit (events.js:198:13)
> at TLSSocket.socketErrorListener (_http_client.js:401:9)
> at TLSSocket.emit (events.js:198:13)
> at emitErrorNT (internal/streams/destroy.js:91:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
> at process._tickCallback (internal/process/next_tick.js:63:19)

adding this fixed it
const { HiveBot } = require('/home/user/node_modules/hive-bot/src/loader.js');
